### ISSUE TITLE
UNKNOWN_VALUE in the Masked Carnevallian's Monster Carnival feature

### ISSUE THREAD

**Issue by FreshRoyal** [MeriadarGoblin/elements-ffxiv#10]

**Comment by MeriadarGoblin** [comment]
Noted, working on now.

**Comment by MeriadarGoblin** [comment]
Fixed and made the sheet description a little shorter.
https://github.com/MeriadarGoblin/elements-ffxiv/commit/0e224670fa6a3d923763abb946912afb61e45324
