### ISSUE TITLE
Incorrect ID for Ninja

### ISSUE THREAD

**Issue by CocoNybbles** [MeriadarGoblin/elements-ffxiv#11]
The ninja hasn't got a new ID, it's "ID_WOTC_PHB_ARCHETYPE_ASSASSIN", therefore the normal Rogue Assassin will be overriden upon loading up AuroraBuilder.

<element name="Ninja" type="Archetype" source="5th Edition D&amp;D x Final Fantasy XIV - Classes and Races Compendium" id="ID_WOTC_PHB_ARCHETYPE_ASSASSIN">

**Comment by MeriadarGoblin** [comment]
Thank you for catching that. It should be fixed now.
