### ISSUE TITLE
RDM Multiclass and adjustments

### ISSUE THREAD

**Issue by HashiruYodokaze** [MeriadarGoblin/elements-ffxiv#6]
RDM doesn't appear on multiclass list despite pre-requisites being met with character, appears not to have the multiclass section in the XML file that was added to other classes.

**Comment by HashiruYodokaze** [comment]
Also noted misspelling for Lalafellin Nimbleness as "Lalafelling".
Titan-Egi's movement speed is listed as "0 ft." despite having "hover 30 ft." in the source material. Problem is also present on both Ifrit-Egi and Garuda-Egi. This may be a problem with the sheet generator (since it lists 'hover 30ft.' in the companion selection interface), but wanted to note it nonetheless.

**Comment by MeriadarGoblin** [comment]
Noted! Got the fixes to RDM, thanks for looking at Lalafell for me! As for the egi, there is no internal support of companion hover so it is now changed to "fly".
